# Generated by Django 4.0.4 on 2022-11-02 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='property_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
