# Generated by Django 4.0.4 on 2022-11-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='property_id',
            field=models.CharField(max_length=200),
        ),
    ]
