# Generated by Django 4.0.4 on 2022-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.FloatField()),
                ('m2', models.FloatField()),
                ('property_type', models.CharField(blank=True, choices=[('DEPARTAMENTO', 'Apartment'), ('CASA', 'House'), ('CASA_EN_CONDOMINIO', 'Condo'), ('OFICINA', 'Office'), ('DESCONOCIDO', 'Unknown')], max_length=30, null=True)),
                ('city', models.CharField(blank=True, default='Ciudad de México', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='Ciudad de México', max_length=100, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ext_number', models.CharField(blank=True, max_length=20, null=True)),
                ('int_number', models.CharField(blank=True, max_length=50, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
